name: radiologiev2
version: 1.0.0+1
publish_to: none
description: radiologie
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  xml: ^5.3.1
  http: ^0.13.4
  flutter_signin_button: ^2.0.0
  dio: ^4.0.4
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

