name: radiologiev2
version: 1.0.0+1
publish_to: none
description: radiologie
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  intl_phone_field: ^3.0.1
  dropdown_search: ^2.0.1
  datetime_picker_formfield: ^2.0.0
  flutter_slidable: ^1.2.0
  font_awesome_flutter: ^10.1.0

  time_planner: ^0.0.4
  get: ^4.6.1
  xml: ^5.3.1
  http: ^0.13.4
  flutter_agenda: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0


  flutter:
    sdk: flutter
#  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

